In [1]:
# Read the data into df
import numpy as np
import pandas as pd
df=pd.read_csv("Orange_Telecom_Churn_Data.csv")
df

     state\taccount_length\tarea_code\tphone_number\tintl_plan\tvoice_mail_plan\tnumber_vmail_messages\ttotal_day_minutes\ttotal_day_calls\ttotal_day_charge\ttotal_eve_minutes\ttotal_eve_calls\ttotal_eve_charge\ttotal_night_minutes\ttotal_night_calls\ttotal_night_charge\ttotal_intl_minutes\ttotal_intl_calls\ttotal_intl_charge\tnumber_customer_service_calls\tchurned
0     KS\t128\t415\t382-4657\tno\tyes\t25\t265.1\t11...
1     OH\t107\t415\t371-7191\tno\tyes\t26\t161.6\t12...
2     NJ\t137\t415\t358-1921\tno\tno\t0\t243.4\t114\...
3     OH\t84\t408\t375-9999\tyes\tno\t0\t299.4\t71\t...
4     OK\t75\t415\t330-6626\tyes\tno\t0\t166.7\t113\...
5     AL\t118\t510\t391-8027\tyes\tno\t0\t223.4\t98\...
6     MA\t121\t510\t355-9993\tno\tyes\t24\t218.2\t88...
7     MO\t147\t415\t329-9001\tyes\tno\t0\t157\t79\t2...
8     LA\t117\t408\t335-4719\tno\tno\t0\t184.5\t97\t...
9     WV\t141\t415\t330-8173\tyes\tyes\t37\t258.6\t8...
10    IN\t65\t415\t329-6603\tno\tno\t0\t129.1\t137\t...
11    RI\t74\t415\t344-9403\tno\tno\t0\t187.7\t127\t...
12    IA\t168\t408\t363-1107\tno\tno\t0\t128.8\t96\t...
13    MT\t95\t510\t394-8006\tno\tno\t0\t156.6\t88\t2...
14    IA\t62\t415\t366-9238\tno\tno\t0\t120.7\t70\t2...
15    NY\t161\t415\t351-7269\tno\tno\t0\t332.9\t67\t...
16    ID\t85\t408\t350-8884\tno\tyes\t27\t196.4\t139...
17    VT\t93\t510\t386-2923\tno\tno\t0\t190.7\t114\t...
18    VA\t76\t510\t356-2992\tno\tyes\t33\t189.7\t66\...
19    TX\t73\t415\t373-2782\tno\tno\t0\t224.4\t90\t3...
20    FL\t147\t415\t396-5800\tno\tno\t0\t155.1\t117\...
21    CO\t77\t408\t393-7984\tno\tno\t0\t62.4\t89\t10...
22    AZ\t130\t415\t358-1958\tno\tno\t0\t183\t112\t3...
23    SC\t111\t415\t350-2565\tno\tno\t0\t110.4\t103\...
24    VA\t132\t510\t343-4696\tno\tno\t0\t81.1\t86\t1...
25    NE\t174\t415\t331-3698\tno\tno\t0\t124.3\t76\t...
26    WY\t57\t408\t357-3817\tno\tyes\t39\t213\t115\t...
27    MT\t54\t408\t418-6412\tno\tno\t0\t134.3\t73\t2...
28    MO\t20\t415\t353-2630\tno\tno\t0\t190\t109\t32...
29    HI\t49\t510\t410-7789\tno\tno\t0\t119.3\t117\t...
...                                                 ...
4970  MD\t133\t415\t363-2715\tno\tno\t0\t173.1\t126\...
4971  HI\t128\t510\t409-8074\tno\tyes\t28\t115.4\t96...
4972  FL\t81\t408\t357-1624\tno\tno\t0\t190.9\t92\t3...
4973  ND\t81\t415\t342-2543\tno\tno\t0\t234.1\t105\t...
4974  LA\t96\t408\t347-4427\tno\tno\t0\t102.1\t74\t1...
4975  AR\t93\t415\t411-9580\tno\tno\t0\t131.9\t91\t2...
4976  KY\t145\t408\t338-1170\tno\tno\t0\t135\t122\t2...
4977  HI\t53\t510\t356-5217\tyes\tno\t0\t145\t80\t24...
4978  KS\t108\t408\t389-4921\tno\tno\t0\t170.3\t48\t...
4979  TX\t52\t415\t330-3162\tno\tno\t0\t188.7\t99\t3...
4980  WA\t73\t408\t408-8236\tno\tno\t0\t177.2\t118\t...
4981  NC\t61\t510\t408-3742\tno\tno\t0\t7.2\t97\t1.2...
4982  TX\t86\t408\t360-8716\tno\tno\t0\t181.1\t124\t...
4983  LA\t137\t408\t400-1731\tno\tno\t0\t151.8\t90\t...
4984  TN\t74\t510\t341-2423\tno\tno\t0\t159.4\t86\t2...
4985  NC\t118\t510\t344-6099\tno\tyes\t31\t226.6\t99...
4986  OH\t125\t415\t364-2584\tno\tno\t0\t214.7\t115\...
4987  AR\t127\t415\t397-4141\tno\tyes\t27\t157.6\t10...
4988  WA\t80\t510\t397-4475\tno\tno\t0\t157\t101\t26...
4989  MN\t150\t408\t407-6315\tno\tno\t0\t170\t115\t2...
4990  ND\t140\t510\t364-8203\tno\tno\t0\t244.7\t115\...
4991  AZ\t97\t510\t410-3888\tno\tno\t0\t252.6\t89\t4...
4992  MT\t83\t415\t355-3630\tno\tno\t0\t188.3\t70\t3...
4993  WV\t73\t408\t411-9655\tno\tno\t0\t177.9\t89\t3...
4994  NC\t75\t408\t417-1886\tno\tno\t0\t170.7\t101\t...
4995  HI\t50\t408\t365-8751\tno\tyes\t40\t235.7\t127...
4996  WV\t152\t415\t334-9736\tno\tno\t0\t184.2\t90\t...
4997  DC\t61\t415\t333-6861\tno\tno\t0\t140.6\t89\t2...
4998  DC\t109\t510\t394-2206\tno\tno\t0\t188.8\t67\t...
4999  VT\t86\t415\t373-8058\tno\tyes\t34\t129.4\t102...

[5000 rows x 1 columns]

In [2]:
# Display the top five rows
df.head()

  state\taccount_length\tarea_code\tphone_number\tintl_plan\tvoice_mail_plan\tnumber_vmail_messages\ttotal_day_minutes\ttotal_day_calls\ttotal_day_charge\ttotal_eve_minutes\ttotal_eve_calls\ttotal_eve_charge\ttotal_night_minutes\ttotal_night_calls\ttotal_night_charge\ttotal_intl_minutes\ttotal_intl_calls\ttotal_intl_charge\tnumber_customer_service_calls\tchurned
0  KS\t128\t415\t382-4657\tno\tyes\t25\t265.1\t11...
1  OH\t107\t415\t371-7191\tno\tyes\t26\t161.6\t12...
2  NJ\t137\t415\t358-1921\tno\tno\t0\t243.4\t114\...
3  OH\t84\t408\t375-9999\tyes\tno\t0\t299.4\t71\t...
4  OK\t75\t415\t330-6626\tyes\tno\t0\t166.7\t113\...

In [3]:
# Display the last three rows
df.tail(3)

     state\taccount_length\tarea_code\tphone_number\tintl_plan\tvoice_mail_plan\tnumber_vmail_messages\ttotal_day_minutes\ttotal_day_calls\ttotal_day_charge\ttotal_eve_minutes\ttotal_eve_calls\ttotal_eve_charge\ttotal_night_minutes\ttotal_night_calls\ttotal_night_charge\ttotal_intl_minutes\ttotal_intl_calls\ttotal_intl_charge\tnumber_customer_service_calls\tchurned
4997  DC\t61\t415\t333-6861\tno\tno\t0\t140.6\t89\t2...
4998  DC\t109\t510\t394-2206\tno\tno\t0\t188.8\t67\t...
4999  VT\t86\t415\t373-8058\tno\tyes\t34\t129.4\t102...

In [4]:
# Check the total number of entries you have
print(df.shape)
print(df.count())

(5000, 1)
state\taccount_length\tarea_code\tphone_number\tintl_plan\tvoice_mail_plan\tnumber_vmail_messages\ttotal_day_minutes\ttotal_day_calls\ttotal_day_charge\ttotal_eve_minutes\ttotal_eve_calls\ttotal_eve_charge\ttotal_night_minutes\ttotal_night_calls\ttotal_night_charge\ttotal_intl_minutes\ttotal_intl_calls\ttotal_intl_charge\tnumber_customer_service_calls\tchurned    5000
dtype: int64

In [5]:
# Check the No of features
print(df.shape[0])
print(df.shape[1]) # cols

5000
1

In [6]:

# Print features Names(Column Names)
df.columns

Index(['state\taccount_length\tarea_code\tphone_number\tintl_plan\tvoice_mail_plan\tnumber_vmail_messages\ttotal_day_minutes\ttotal_day_calls\ttotal_day_charge\ttotal_eve_minutes\ttotal_eve_calls\ttotal_eve_charge\ttotal_night_minutes\ttotal_night_calls\ttotal_night_charge\ttotal_intl_minutes\ttotal_intl_calls\ttotal_intl_charge\tnumber_customer_service_calls\tchurned'], dtype='object')

In [7]:

# Print the row indices of the dataframe
df.index

RangeIndex(start=0, stop=5000, step=1)

In [8]:
# Check the dtype of each and every columns
df.dtypes

state\taccount_length\tarea_code\tphone_number\tintl_plan\tvoice_mail_plan\tnumber_vmail_messages\ttotal_day_minutes\ttotal_day_calls\ttotal_day_charge\ttotal_eve_minutes\ttotal_eve_calls\ttotal_eve_charge\ttotal_night_minutes\ttotal_night_calls\ttotal_night_charge\ttotal_intl_minutes\ttotal_intl_calls\ttotal_intl_charge\tnumber_customer_service_calls\tchurned    object
dtype: object

In [9]:
# Description for Numerical Column min,max,count,25%,50%,75%,std
df.describe()

       state\taccount_length\tarea_code\tphone_number\tintl_plan\tvoice_mail_plan\tnumber_vmail_messages\ttotal_day_minutes\ttotal_day_calls\ttotal_day_charge\ttotal_eve_minutes\ttotal_eve_calls\ttotal_eve_charge\ttotal_night_minutes\ttotal_night_calls\ttotal_night_charge\ttotal_intl_minutes\ttotal_intl_calls\ttotal_intl_charge\tnumber_customer_service_calls\tchurned
count                                                5000
unique                                               5000
top     KS\t152\t408\t357-8842\tno\tyes\t39\t243.1\t13...
freq                                                    1

In [10]:
# Description for the categorical Columns count,top,freq
df.describe(include=object)

       state\taccount_length\tarea_code\tphone_number\tintl_plan\tvoice_mail_plan\tnumber_vmail_messages\ttotal_day_minutes\ttotal_day_calls\ttotal_day_charge\ttotal_eve_minutes\ttotal_eve_calls\ttotal_eve_charge\ttotal_night_minutes\ttotal_night_calls\ttotal_night_charge\ttotal_intl_minutes\ttotal_intl_calls\ttotal_intl_charge\tnumber_customer_service_calls\tchurned
count                                                5000
unique                                               5000
top     KS\t152\t408\t357-8842\tno\tyes\t39\t243.1\t13...
freq                                                    1

In [11]:
# Missing value count column wise
df.isnull().sum()

state\taccount_length\tarea_code\tphone_number\tintl_plan\tvoice_mail_plan\tnumber_vmail_messages\ttotal_day_minutes\ttotal_day_calls\ttotal_day_charge\ttotal_eve_minutes\ttotal_eve_calls\ttotal_eve_charge\ttotal_night_minutes\ttotal_night_calls\ttotal_night_charge\ttotal_intl_minutes\ttotal_intl_calls\ttotal_intl_charge\tnumber_customer_service_calls\tchurned    0
dtype: int64

In [12]:
# Total Missing values count in the DataFrame
df.isnull().sum().sum()

0

In [ ]:
# If there are any missing values replace them.
# Ans:There is no missing values in data

In [13]:
# Check the output for the info function
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 1 columns):
state	account_length	area_code	phone_number	intl_plan	voice_mail_plan	number_vmail_messages	total_day_minutes	total_day_calls	total_day_charge	total_eve_minutes	total_eve_calls	total_eve_charge	total_night_minutes	total_night_calls	total_night_charge	total_intl_minutes	total_intl_calls	total_intl_charge	number_customer_service_calls	churned    5000 non-null object
dtypes: object(1)
memory usage: 39.1+ KB

In [19]:
# Access 3,5,7 columns using iloc,loc and without using any of them
df=pd.read_csv("Orange_Telecom_Churn_Data.csv")
print(df.iloc[:,3:8:2])
print("*"*50)
print(df.loc[:,["phone_number","voice_mail_plan","total_day_minutes"]])
print("*"*50)
df[["phone_number","voice_mail_plan","total_day_minutes"]]

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[5000 rows x 0 columns]
**************************************************

KeyError: "None of [['phone_number', 'voice_mail_plan', 'total_day_minutes']] are in the [columns]"

In [20]:
# How many unique states are there
df=pd.read_csv("Orange_Telecom_Churn_Data.csv")
df.state.nunique()

AttributeError: 'DataFrame' object has no attribute 'state'

In [16]:
df

     state\taccount_length\tarea_code\tphone_number\tintl_plan\tvoice_mail_plan\tnumber_vmail_messages\ttotal_day_minutes\ttotal_day_calls\ttotal_day_charge\ttotal_eve_minutes\ttotal_eve_calls\ttotal_eve_charge\ttotal_night_minutes\ttotal_night_calls\ttotal_night_charge\ttotal_intl_minutes\ttotal_intl_calls\ttotal_intl_charge\tnumber_customer_service_calls\tchurned
0     KS\t128\t415\t382-4657\tno\tyes\t25\t265.1\t11...
1     OH\t107\t415\t371-7191\tno\tyes\t26\t161.6\t12...
2     NJ\t137\t415\t358-1921\tno\tno\t0\t243.4\t114\...
3     OH\t84\t408\t375-9999\tyes\tno\t0\t299.4\t71\t...
4     OK\t75\t415\t330-6626\tyes\tno\t0\t166.7\t113\...
5     AL\t118\t510\t391-8027\tyes\tno\t0\t223.4\t98\...
6     MA\t121\t510\t355-9993\tno\tyes\t24\t218.2\t88...
7     MO\t147\t415\t329-9001\tyes\tno\t0\t157\t79\t2...
8     LA\t117\t408\t335-4719\tno\tno\t0\t184.5\t97\t...
9     WV\t141\t415\t330-8173\tyes\tyes\t37\t258.6\t8...
10    IN\t65\t415\t329-6603\tno\tno\t0\t129.1\t137\t...
11    RI\t74\t415\t344-9403\tno\tno\t0\t187.7\t127\t...
12    IA\t168\t408\t363-1107\tno\tno\t0\t128.8\t96\t...
13    MT\t95\t510\t394-8006\tno\tno\t0\t156.6\t88\t2...
14    IA\t62\t415\t366-9238\tno\tno\t0\t120.7\t70\t2...
15    NY\t161\t415\t351-7269\tno\tno\t0\t332.9\t67\t...
16    ID\t85\t408\t350-8884\tno\tyes\t27\t196.4\t139...
17    VT\t93\t510\t386-2923\tno\tno\t0\t190.7\t114\t...
18    VA\t76\t510\t356-2992\tno\tyes\t33\t189.7\t66\...
19    TX\t73\t415\t373-2782\tno\tno\t0\t224.4\t90\t3...
20    FL\t147\t415\t396-5800\tno\tno\t0\t155.1\t117\...
21    CO\t77\t408\t393-7984\tno\tno\t0\t62.4\t89\t10...
22    AZ\t130\t415\t358-1958\tno\tno\t0\t183\t112\t3...
23    SC\t111\t415\t350-2565\tno\tno\t0\t110.4\t103\...
24    VA\t132\t510\t343-4696\tno\tno\t0\t81.1\t86\t1...
25    NE\t174\t415\t331-3698\tno\tno\t0\t124.3\t76\t...
26    WY\t57\t408\t357-3817\tno\tyes\t39\t213\t115\t...
27    MT\t54\t408\t418-6412\tno\tno\t0\t134.3\t73\t2...
28    MO\t20\t415\t353-2630\tno\tno\t0\t190\t109\t32...
29    HI\t49\t510\t410-7789\tno\tno\t0\t119.3\t117\t...
...                                                 ...
4970  MD\t133\t415\t363-2715\tno\tno\t0\t173.1\t126\...
4971  HI\t128\t510\t409-8074\tno\tyes\t28\t115.4\t96...
4972  FL\t81\t408\t357-1624\tno\tno\t0\t190.9\t92\t3...
4973  ND\t81\t415\t342-2543\tno\tno\t0\t234.1\t105\t...
4974  LA\t96\t408\t347-4427\tno\tno\t0\t102.1\t74\t1...
4975  AR\t93\t415\t411-9580\tno\tno\t0\t131.9\t91\t2...
4976  KY\t145\t408\t338-1170\tno\tno\t0\t135\t122\t2...
4977  HI\t53\t510\t356-5217\tyes\tno\t0\t145\t80\t24...
4978  KS\t108\t408\t389-4921\tno\tno\t0\t170.3\t48\t...
4979  TX\t52\t415\t330-3162\tno\tno\t0\t188.7\t99\t3...
4980  WA\t73\t408\t408-8236\tno\tno\t0\t177.2\t118\t...
4981  NC\t61\t510\t408-3742\tno\tno\t0\t7.2\t97\t1.2...
4982  TX\t86\t408\t360-8716\tno\tno\t0\t181.1\t124\t...
4983  LA\t137\t408\t400-1731\tno\tno\t0\t151.8\t90\t...
4984  TN\t74\t510\t341-2423\tno\tno\t0\t159.4\t86\t2...
4985  NC\t118\t510\t344-6099\tno\tyes\t31\t226.6\t99...
4986  OH\t125\t415\t364-2584\tno\tno\t0\t214.7\t115\...
4987  AR\t127\t415\t397-4141\tno\tyes\t27\t157.6\t10...
4988  WA\t80\t510\t397-4475\tno\tno\t0\t157\t101\t26...
4989  MN\t150\t408\t407-6315\tno\tno\t0\t170\t115\t2...
4990  ND\t140\t510\t364-8203\tno\tno\t0\t244.7\t115\...
4991  AZ\t97\t510\t410-3888\tno\tno\t0\t252.6\t89\t4...
4992  MT\t83\t415\t355-3630\tno\tno\t0\t188.3\t70\t3...
4993  WV\t73\t408\t411-9655\tno\tno\t0\t177.9\t89\t3...
4994  NC\t75\t408\t417-1886\tno\tno\t0\t170.7\t101\t...
4995  HI\t50\t408\t365-8751\tno\tyes\t40\t235.7\t127...
4996  WV\t152\t415\t334-9736\tno\tno\t0\t184.2\t90\t...
4997  DC\t61\t415\t333-6861\tno\tno\t0\t140.6\t89\t2...
4998  DC\t109\t510\t394-2206\tno\tno\t0\t188.8\t67\t...
4999  VT\t86\t415\t373-8058\tno\tyes\t34\t129.4\t102...

[5000 rows x 1 columns]

In [17]:
# How many customers are churned
df.churned.sum()

AttributeError: 'DataFrame' object has no attribute 'churned'

In [18]:
# How many are not churned
df.churned.value_counts()

AttributeError: 'DataFrame' object has no attribute 'churned'